### ISSUE TITLE
Analysis of E-learning platfrom: Khan academy

### ISSUE THREAD

**Issue by TheDude957** [JR-prog/SOEN342_Team_F#1]
Analyze what the platform offers in terms of features and products available.
Link: https://www.khanacademy.org

**Comment by TheDude957** [comment]
I created a doc that has images from the the site. I signed up as a teacher, student, and parent to get a sense of the different features. As a parent I added my "child" and enrolled said child into a course I created as teacher user and then promptly assigned homework due the next day to the class.

# General concept
Khan academy is a non-profit e-academy website where teachers, parents and learners to come together to one platform to tutor learners. Khan academy provides a vast array of courses from pre K to college level content through video lectures and practice problems.

###  Different types of users
Khan academy has 3 main users for their platform. Learners are the user that will enroll in courses and hopefully learn stuff. Teachers can be teachers from an actual school and can create a class through khan academy and monitor their students progress in the khan academy courses. Teachers can be parents, the third user, who can create accounts for their children and monitor their progress as well as create course to teach/tutor and enroll in khan academy courses themselves.

# Users
This section will describe the different actions users can do

### Teachers
Teachers can create a class where they choose from pre made courses made by khan academy and add students and then tutor those students.

#### Teacher settings
Can create class code to allow other students to join classroom. 
![image](https://user-images.githubusercontent.com/52092026/193433428-a0055ffd-ed94-4991-9931-8e08345680c0.png)

#### Student roster
Can see all students + email. Action allowed on students includes adding to course, removing from course and stop coaching.
![image](https://user-images.githubusercontent.com/52092026/193433423-77b70ea5-35a0-4b6b-b951-cc87e74c863a.png)

#### Assignment management
Can select portion of course (ie video lectures, worksheets and quizzes) to students and set a due date. Teacher can then see student’s scores on the material assigned to them. Teacher also has a dashboard to see how far students are in their assignments. Teachers can also create mastery goals where students have to achieve a certain percentage of the course.
![image](https://user-images.githubusercontent.com/52092026/193433408-8bf25167-42d5-433c-9ba2-5b2e75713fc6.png)
![image](https://user-images.githubusercontent.com/52092026/193433419-4897934e-9a73-420c-97b6-3cfb768d85ad.png)

### Parents
#### parent dashboard
In this dashboard parents can add children that they can supervise over
![image](https://user-images.githubusercontent.com/52092026/193433398-289d32ed-fcca-4305-b20b-2ee9959c25c5.png)


#### Child settings
The parent can edit details about the child (name, birthdate, video playback features and be able to delete the child (as in remove the account from the platform duh) ) Can also change password.
![image](https://user-images.githubusercontent.com/52092026/193433395-209ca46a-bf11-4af2-bd4b-4ec4cf635afa.png)


#### Child profile
Parent can view their child’s profile and see their progress in courses, their badges earned and see their statistics.
![image](https://user-images.githubusercontent.com/52092026/193433390-34a503b1-1510-4e67-b55c-cbe29c4986c3.png)

### Learners
Learners can view the same content such as their profile and progress that can be seen by their parents and the images for which have been shown in the section above. The learner can enroll in courses both through a class taught by a teacher and on their own to follow courses given by khan academy where there is no teacher managing the course. Furthermore as shown in above where the teacher assigned work, this can be seen from the student side where there are assignments due for the next day created by mr. potatohead’s class. 
![image](https://user-images.githubusercontent.com/52092026/193433381-1f6efc64-ef60-4c9b-87ff-02a466fc49ea.png)


# Courses
### Course selection
![image](https://user-images.githubusercontent.com/52092026/193433353-1be1ec93-33e8-432a-9254-22cff1fb0513.png)

### Specific course
In a specific there are multiple video lectures per section. For every video watched and assignment done, students get mastery points which is supposed to represent how much they’ve mastered a topic. If a student completes an assignment correctly and the quizzes that go with the course then it can be said that the student has mastered the course. The course also provides unit tests for each unit and then a test for the whole course.
![image](https://user-images.githubusercontent.com/52092026/193433365-0c179cb4-b48b-41f2-aec9-9db52cbcdbc9.png)
![image](https://user-images.githubusercontent.com/52092026/193433370-70b1c3f3-1efc-4999-ae44-47905296feca.png)

**Comment by Anjalibhardwaj1** [comment]
These are just _some_ features I observed:
**As a Guests** 
   Are able to browse per-recorded video's for different subjects.
   Are able to log in or sign up as a Teacher, Student or Parent
   Are able to contact the Help centre
   Are able to view information and articles about Khan Academy 
**As a Teacher**
   Are able to select an existing course name or create their own
   Are able to access a database that includes all the names, emails, and the course registered of their students.
   Have access to additional resources page which includes, helpful articles, additional settings for the teacher
   Are able to import google classroom 
   Are able to see submitted projects
   Are able to give feedback on students work and see student progress
**As a Parent**
  Are able to enrol a child in a class
  Get access to parent resources (helpful articles etc.)
**As a Student** 
   Are able to join a classroom using a code
   Are able to edit their profiles
   Are able to access per-recorded videos
   Are able to see their own progress 
**Interacting with support**
   Help centre is open to every kind of user and mainly consists of articles or getting support from the community
   No phone support
   Email support by ticket
