### ISSUE TITLE
Vision Document - Positioning

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#10]
In this section, we have to provide a **problem statement** and a **product position statement**. The problem statement involves defining the problem we are solving, it's impact on stakeholders, and what a successful solution would be. The product position statement just aims to describe how our product compares to others in the market.

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by jay-roe** [comment]
## Positioning
### Problem Statement
Proper education is both expensive and hard to find. Conventional tutoring can be effective, but it is not accessible to everyone financially and is not guaranteed to be successful, as every individual learns and understands concepts in different ways. This affects both the learners trying to expand their knowledge as well as the tutors who wish to share theirs. As a result, it is difficult for people who wish to improve in certain domains to find adequate and consistent support. To address the issues of financial accessibility, a successful solution would be to offer different services than the typical 1-on-1 tutoring that are less costly but still allow tutors to be compensated fairly. On the issue of the quality of the education, a successful solution would be to offer a larger network of tutors, each with their own unique teaching approach, to ensure that each learner can find a tutor whose teaching style is compatible with the way they learn. To address the consistency of the learner's support, a successful solution would be to allow learners to get answers to their specific questions asynchronously.

### Product Position Statement
A+ Academy is a solution aimed towards ***ALL*** students and tutors who wish to have a quality learning/teaching environement all while being economically viable. A+ Academy is a tutoring swiss army knife that provides various services working harmoniously to provide affordable quality tutoring. Unlike typical tutoring platforms such as School Success, tutors are not directly assigned to learners, allowing learners and tutors alike to find the optimal match. Furthermore, unlike other tutoring marketplaces such as Super Prof,  A+ Academy offers cheaper group sessions, as well as access to an online Learning Forum™️ which allows learners to asynchronously receive answers to their questions from any qualified tutor.

**Comment by michaelroubeiz** [comment]
Good work!! I think that "student" would be a better term over "learner" since in Phase 1 we used "student".

**Comment by michaelroubeiz** [comment]
Also should we fit these paragraphs into the table provided on the word doc?

**Comment by TheDude957** [comment]
Fitting them in the table provides a more concise and readable format that would allow someone to easily scan through the document and know the who what where etc without getting bogged down into reading a cumbersome paragraph

**Comment by jay-roe** [comment]
Thanks for the feedback, the answers have already been fit into the table, per Ahmed's feedback on Tuesday.
