### ISSUE TITLE
Vision Document - Stakeholder Descriptions

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#11]
In this section we need to provide a stakeholder summary, user summary, user environment, and key stakeholder or user needs. For each section, we must fill out the provided table with the appropriate information.

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by michaelroubeiz** [comment]
The following subsections of 3. Stakeholder Descriptions have been completed:
3.1 Stakeholder Summary
3.2 User Summary
3.3 User Environment
3.4 Key Stakeholder or User Needs
