### ISSUE TITLE
Vision Document - Product Overview

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#12]
In this section we need the product perspective as well as the assumptions and dependencies of our solution. The product perspective section puts the product in perspective with regards to other products and the environment. The assumptions and dependencies are just a list of factors that affect our product's features.

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by michaelroubeiz** [comment]
https://tokbox.com/developer/embeds/ 
Could this be a video call dependency we can add?

**Comment by jay-roe** [comment]
> https://tokbox.com/developer/embeds/
Could this be a video call dependency we can add?


Yes, this looks exactly like what we would need to create our own online learning space.

**Comment by melisa1026** [comment]
ok, I added the video api to this section and it's now complete
