### ISSUE TITLE
Vision Document - Product Features

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#13]
In this section we actually need to list and describe our core features (which we already kinda did in part 1!). We also need to list other non functional requirements in a separate section.

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by TheDude957** [comment]
A enumerated approach might be more concise and readable to discern between the different core features

**Comment by aberhenegousse** [comment]
@TheDude957 Thanks for your feedback, added enumeration of the core features, hopefully it's more clear now

**Comment by michaelroubeiz** [comment]
Looks good. Nice content and formatting.
