### ISSUE TITLE
Vision Document - Risk and Feasibility

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#14]
This section includes a part on risk assessment and proposed mitigation techniques. We also need to assess the technical, financial and organizational feasibility of our product.

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by MrMelon1232** [comment]
Risks have been added to a table. Review is needed for this section.

**Comment by Anjalibhardwaj1** [comment]
I will look it over

**Comment by melisa1026** [comment]
Feasibility sections have been written

**Comment by MrMelon1232** [comment]
First and second risk might be too similar, a review is needed for this.

**Comment by TheDude957** [comment]
> First and second risk might be too similar, a review is needed for this.

You could split it where 1. is for hackers and 2. is for non human actors ie bots

**Comment by MrMelon1232** [comment]
> > First and second risk might be too similar, a review is needed for this.
> 
> You could split it where 1. is for hackers and 2. is for non human actors ie bots

sounds good, I did the split just need a final review and we can close the issue

**Comment by melisa1026** [comment]
just reviewed it, everything looks good
