### ISSUE TITLE
Vision Document - Use Case Diagram

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#15]
Pretty self explanatory :^)

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

Please link any online resources used (like an online visual paradigm link, so everyone can easily view and edit).

**Comment by TheDude957** [comment]
https://lucid.app/lucidchart/1b98a218-4910-4e86-a98e-cd5ae323f37f/edit?viewport_loc=-172%2C92%2C2219%2C1097%2C.Q4MUjXso07N&invitationId=inv_d31fe5e4-3b3e-4039-b7a4-c4c359eb4782

link to work on use case diagram. Require sign up but its free and pretty intuitive software

**Comment by TheDude957** [comment]
my thoughts:
Actors:
Parent
Student
Tutor
Administrator
Guest

Use cases
Account creation
course
forum
make payment
direct messaging

**Comment by michaelroubeiz** [comment]
I think tutor should be considered a primary actor

**Comment by TheDude957** [comment]
is primary indicated by which side of the diagram they are on?

**Comment by mikeflof** [comment]
if I remember correctly, ya. Left is primary, right is secondary.

**Comment by michaelroubeiz** [comment]
> is primary indicated by which side of the diagram they are on?

if I remember correctly, ya. Left is primary, right is secondary.

**Comment by TheDude957** [comment]
I only orded them in a way to make it legible due to the large amount of interactions

**Comment by michaelroubeiz** [comment]
Ill just add something to specify that it's also a primary actor

**Comment by jay-roe** [comment]
Fixed a few typos. Looks great! Let's let someone else share their thoughts and close if good.

**Comment by michaelroubeiz** [comment]
Should we add an actor for payment system and Vonage Video API? Im looking at examples and it seems that sometimes they add in dependencies or at least the payment system 
<img width="411" alt="Screenshot 2022-11-01 at 9 05 49 PM" src="https://user-images.githubusercontent.com/35436139/199370710-c2211f2d-d57c-4ad1-a07c-9c2b4170258b.png">

**Comment by mikeflof** [comment]
<img width="411" alt="Screenshot 2022-11-01 at 9 05 49 PM" src="https://user-images.githubusercontent.com/35436139/199370710-c2211f2d-d57c-4ad1-a07c-9c2b4170258b.png">

**Comment by michaelroubeiz** [comment]
Also in all examples in Slide 16 on Moodle there are no names on the associations for use case diagram.

**Comment by TheDude957** [comment]
![image](https://user-images.githubusercontent.com/62126231/199375199-be5f9787-2d3e-44e4-b1f0-ef9d734ce002.png)

**Comment by TheDude957** [comment]
![image](https://user-images.githubusercontent.com/62126231/199375283-647b185d-ea9c-4880-82c0-e2e58f9ac7f3.png)

**Comment by michaelroubeiz** [comment]
these are specific titles so I think we should adjust all the ones there to these words + <\<extends>\>

**Comment by jay-roe** [comment]
I agree with Michael, after looking at some of the examples in the slides, our diagram has some inconsistencies with the stuff we learned in class.
Ex:
- Using verbs for use cases is a must
- Associations don't seem to have names describing them (this is not a UML class diagram)
- etc.

**Comment by michaelroubeiz** [comment]
Great, use case diagram is updated and complete.
