### ISSUE TITLE
GUI Mockup

### ISSUE THREAD

**Issue by michaelroubeiz** [JR-prog/SOEN342_Team_F#16]
Create mockups for the main pages of A+ Academy.
Pages will need to be selected.
Figma Link:
https://www.figma.com/file/HP7yiU9Fgc8dKmZYu5Iwrt/Untitled?node-id=0%3A1&t=K0aGD4KzzIfzC4Vk-1

**Comment by jay-roe** [comment]
Done. https://www.figma.com/file/HP7yiU9Fgc8dKmZYu5Iwrt/A+-Academy?node-id=0%3A1&t=oh7DRgm1eY3iAeXL-0
