### ISSUE TITLE
Analysis of E-learning platform: Succes Scolaire 

### ISSUE THREAD

**Issue by TheDude957** [JR-prog/SOEN342_Team_F#3]
Analyze what the platform offers in terms of features and products available.
Link: https://www.successcolaire.ca

**Comment by aberhenegousse** [comment]
**General goals**
Tutoring services for primary, secondary and college students. Tutors may work with parents and teachers to help students. 
- Ask for a tutor
- Become a tutor
- Join online group classes. Registration: school, grade, …
- Show stats on site: number of tutors, number of tutees, percent of grades improved, etc..

**Types of services**
Help with homework
Remedial education
Preparation for exams
Enrichment
Summer courses
student athlete
Preparation for admission exams
The School School Success
Home school

**Organization/ Tutoring selection by:**
Subject categories to choose from
Tutoring offered by location, but online available too

**Becoming a tutor**
Submit an application.
They will set up an interview

**Getting a tutor**
Registration/ Request a tutor with text/chat feature that asks user information for personalized profile ( grade, if you’re a parent or student, subject)

**Users:**
Parents
Education professional
Student 
Tutor

**Website features**
frequently asked questions section with answers
chatbox
online class with a some free pre recorded lectures

Tutoring Service Fees: 46$ - 50$ per hour paid to the organization

~ Report by Melisa and Aida <3
