### ISSUE TITLE
Analysis of E-learning platform: Superprof

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#4]
Analyze what the platform offers in terms of features and products available.
Link: https://www.superprof.ca

**Comment by michaelroubeiz** [comment]
**Superprof Findings:**
Can be tutor and student
Very simple website. Not too many pages to navigate to. Intuitive.
Very well designed website

**Creating account/Login:** 
Email, Facebook, Google

**Student/Tutor:**
Receive notifications by sms and email.
Can add Skype ID and Hangouts ID to facilitate tutor calls.
Gender options are only Male and Female 🤔.
Buy gift card for family member.
Messaging page to message tutors and students

**Student:**
Possibility to favourite tutors and view later.
Invoice section. Payment section and can add method.

**Tutor:**
Possibility to upload degree.

**Creating Ad’s:**
Tutors can create ads: how tutors display themselves to students. Tutors are provided a guide of how the ad should be written
Can teach in multiple languages, list the languages
Add your rate per hour 
When ad is live, can view student view
Multiple ads can exist. Possibility to deactivate ads.
Can add a video so potential students can get an idea of who you are
Can set a cancellation policy where you can set how much money you want in case they cancel.
Can get payed after each lesson or at end of month.
When tutor uploads photo the website makes sure there is a face in the photo.

**Pro Pass:** 
“Push in search results and receive up to 3x more lesson requests from our students.” 
Superprof doesn’t take a cut of the money
Get statistics for your ads.
$69 a year

**Comment by jay-roe** [comment]
## Overall features
- option for at home, travel and online lessons
- instant messaging
- payment safety (insurance, cancellation, secure)
- evaluation (ex: 5 star reputation)
- clean and simple UI
- browse ads/tutors
- easy (standard) sign up options (google, facebook, email etc.)
- intuitive help center for both students and tutors
- see tutor response times

## Tutor
### Set up
- simple listing (ad) creation (mostly click only, with option of search)
- easy external sharing of ad (copy link)

### Premium (\$69 annual)
- extra visibility
- no commission
- stats on ads

### Profile
- easy rate management (based on all factors like travel, web etc. and option for packs)
- about lesson
- about you

## User (\$49)
- must pay to request a tutor, and then pay the tutor rates
