### ISSUE TITLE
Part I: Market analysis

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#6]
Comparative study clear with reference to similar systems.

Found in #1 #3 #4

**Comment by michaelroubeiz** [comment]
I have written out the features we decided upon yesterday in Part II: E-Academy presentation
Please review if possible or add any features you believe are missing.

**Comment by MrMelon1232** [comment]
Sections and topics are all separated and written properly in text format. A review is needed before closing issue.

**Comment by michaelroubeiz** [comment]
The work looks good, this issue can be closed.
