### ISSUE TITLE
Vision Document - Introduction

### ISSUE THREAD

**Issue by jay-roe** [JR-prog/SOEN342_Team_F#9]
We need to state the purpose of the vision document as well as reference all documents referred to in the document. 

Here is the draft: https://docs.google.com/document/d/17T7nuYVHERMCsCQaGkSAj6LD93g_7C2g_vsoBfltxO8/edit

**Comment by TheDude957** [comment]
I finished the introduction having put the following subsections:
1.1 purpose
1.2 scope
1.3 definitions
